#!/usr/bin/env bash
# Pulls the model pool into the running `ollama` container and refreshes
# MODELS.md's snapshot table. Requires `make up` (or at least the ollama
# service) already running. Model list mirrors config/models.yaml `pool` —
# keep these in sync if that file changes.
set -euo pipefail

cd "$(dirname "$0")/.."
COMPOSE="docker compose -f deploy/docker-compose.dev.yml --env-file .env"

MODELS=(
  "qwen2.5:7b-instruct"   # M-GEN
  "qwen2.5:3b-instruct"   # M-SMALL
  # Uncomment when the owning sprint lands (avoids pulling multi-GB models
  # nobody can use yet):
  # "qwen2.5-coder:7b-instruct"  # M-CODE, Sprint 9/10 (OPS-1 CodeAssist)
  # "bge-m3"                     # M-EMB, Sprint 7 (mcp-search)
)

echo "Pulling ${#MODELS[@]} model(s) into the ollama container..."
for model in "${MODELS[@]}"; do
  echo "--- ollama pull ${model} ---"
  $COMPOSE exec -T ollama ollama pull "${model}"
done

{
  echo "# Model pool snapshot"
  echo
  echo "Regenerated by \`serving/fetch_models.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
  echo
  echo "| Model | License | Quantization | Notes |"
  echo "|---|---|---|---|"
  echo "| qwen2.5:7b-instruct | Apache-2.0 | Ollama default (Q4_K_M) | M-GEN — doc 01 §2 |"
  echo "| qwen2.5:3b-instruct | Apache-2.0 (verify at pull time) | Ollama default (Q4_K_M) | M-SMALL — doc 01 §2 |"
  echo
  echo "Re-verify each checkpoint's license whenever swapping versions (doc 01 §6)."
} > serving/MODELS.md

echo "Done. See serving/MODELS.md."
